web:
  build: .
  environment:
    SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://user:passwd@hostname:5432"
    LINE_CHANNEL_SECRET: "abc"
    LINE_CHANNEL_ACCESS_TOKEN: "123"

  ports:
    - "8080:8080"

  links:
    - "db"

db:
  image: postgres
  environment:
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "secret"     

  ports:
    - "5432:5432"

  volumes:
    - ./data:/var/lib/postgresql/data
